### ISSUE TITLE
ARM machines

### ISSUE THREAD

**Issue by artemt1** [duracellko/azure-vm-manager#2]
Hi,

With the current version only Classic machines are visible. How we could see ARM machines?

**Comment by duracellko** [comment]
I am sorry, ARM machines are not supported. And to be honest I do not plan to implement this support.

When I started this project, Azure portal supported admin access only (all or nothing). Therefore I created this application to restrict access to VMs.
However, new Azure portal supports access rights with ARM. Therefore I do not see value worth effort implementing ARM support.

Thank you for your understanding.

**Comment by artemt1** [comment]
Sure, thanks anyway!
